# Generated by Django 3.2.4 on 2021-07-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
