# Generated by Django 3.2.4 on 2021-07-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='full_name',
        ),
    ]
